// src/app/features/predictions/predictions.component.ts
import { Component } from '@angular/core';
import { injectData } from '@core/signals/inject-data';
import { PredictionCardComponent } from './components/prediction-card.component';
import { RouterLink } from '@angular/router';
import { Prediction } from '@core/models/prediction';
import { Package } from '@core/models/package';

@Component({
  selector: 'app-predictions',
  templateUrl: './predictions.component.html',
  standalone: true,
  imports: [RouterLink, PredictionCardComponent],
})
export class PredictionsComponent {
  predictions = injectData<Prediction[]>('predictions');
  packages = injectData<Package[]>('packages');
}

<div class="space-y-4">
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold">Predictions</h1>
    <a routerLink="/predictions/new" class="btn btn-primary">New</a>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    @for (prediction of predictions(); track prediction.id) {
      <app-prediction-card [prediction]="prediction" [packages]="packages()" />
    }
  </div>
</div>

// src/routes/predictions/+page.svelte
<script lang="ts">
  import PredictionCard from '$lib/components/PredictionCard.svelte';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  let predictions = data.predictions;
  let packages = data.packages;
</script>

<div class="space-y-6">
  <div class="flex justify-between items-center">
    <h1 class="text-2xl font-bold">Predictions</h1>
    <a href="#/predictions/new" class="btn btn-primary">New</a>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    {#each predictions as prediction (prediction.id)}
      <PredictionCard 
        {prediction} 
        {packages}
      />
    {/each}
  </div>
</div>
